In [1]:
import numpy as np
a= np.array([5,5,5,])
a

array([5, 5, 5])

In [10]:
import numpy as np
#list of lists 
b= np.array ([[5,5,5],[6,6,6],[7,7,7]])
b

array([[5, 5, 5],
       [6, 6, 6],
       [7, 7, 7]])

In [11]:
type(a)

numpy.ndarray

In [13]:
type(b)

numpy.ndarray

In [12]:
len(a)

3

In [14]:
#wiht range of elements 
e= np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [16]:
#with specific range of elements 
f= np.arange(2,40)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [20]:
#continue 
g=np.arange(3,300,3)
g

array([  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
        42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,
        81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117,
       120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156,
       159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195,
       198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234,
       237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273,
       276, 279, 282, 285, 288, 291, 294, 297])

In [25]:
#2d
h=np.ones((2,4))
h

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# 3d array
#making and reshaping a 3d array
c= np.arange(240).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### numpy practice session

In [32]:
## import numpy book in jupyter
a="apple"
a

'apple'

In [33]:
print ("my name is zameer hassan")


my name is zameer hassan
